### PR TITLE
Add fav button 

### PR DESCRIPTION
**Pull request by pthor**
Move avatar to left
Increase the size of the top table view cell on the home page
Decrees the size of all the media table view cells

Favorite button does not refresh in realtime (and idk why) or persist session to session, _yet_!

### CODE REVIEW

**Comment by pthor** [comment]
@wcjohnson11 here comes another

**Comment by pthor** [comment]
@wcjohnson11 Updated with more changes

**Comment by pthor** [comment]
@wcjohnson11 updated this PR with more changes to add video to home page, and a favorites screen

**Comment by wcjohnson11** [comment]
:+1: lgtm!

**Pull request merged**
